/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "outline-variant": "#464554",
        "on-surface": "#dae2fd",
        "inverse-on-surface": "#283044",
        "on-tertiary-fixed-variant": "#5c4300",
        "on-error": "#690005",
        "error": "#ffb4ab",
        "surface-variant": "#2d3449",
        "background": "#0b1326",
        "surface-container-lowest": "#060e20",
        "surface-container-high": "#222a3d",
        "secondary-fixed-dim": "#4edea3",
        "tertiary-fixed-dim": "#f9bd22",
        "on-primary-fixed": "#07006c",
        "error-container": "#93000a",
        "inverse-primary": "#494bd6",
        "on-secondary-fixed-variant": "#005236",
        "on-primary-fixed-variant": "#2f2ebe",
        "surface-dim": "#0b1326",
        "secondary-container": "#00b47d",
        "on-background": "#dae2fd",
        "on-tertiary": "#402d00",
        "tertiary-container": "#b88900",
        "on-primary-container": "#0d0096",
        "on-secondary-container": "#003e28",
        "primary": "#c0c1ff",
        "tertiary": "#f9bd22",
        "inverse-surface": "#dae2fd",
        "primary-fixed": "#e1e0ff",
        "primary-container": "#8083ff",
        "on-primary": "#1000a9",
        "surface-bright": "#31394d",
        "surface": "#0b1326",
        "on-secondary-fixed": "#002113",
        "on-tertiary-container": "#372700",
        "primary-fixed-dim": "#c0c1ff",
        "on-secondary": "#003824",
        "secondary": "#4edea3",
        "on-tertiary-fixed": "#261a00",
        "surface-tint": "#c0c1ff",
        "on-surface-variant": "#c7c4d7",
        "surface-container": "#171f33",
        "secondary-fixed": "#6ffbbe",
        "tertiary-fixed": "#ffdf9f",
        "outline": "#908fa0",
        "on-error-container": "#ffdad6",
        "surface-container-highest": "#2d3449",
        "surface-container-low": "#131b2e"
      },
      fontFamily: {
        "headline": ["Inter", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Manrope", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
    },
  },
  plugins: [],
}
